### ISSUE TITLE
Let us know when it is done

### ISSUE THREAD

**Issue by Hillmanae** [Husseinfo/interfast#3]
I am very excited about this app. I really just want a IF timer without any ads and tracking. This will be great.

Don't give up. I am very much looking forward to it.

**Comment by Husseinfo** [comment]
Hey, it is already [available](https://github.com/Husseinfo/interfast#Download)!

**Comment by Hillmanae** [comment]
Yes, but it does not actually work yet. I hope you will be able to complete it.

**Comment by Husseinfo** [comment]
What is not working exactly?

**Comment by b010b0** [comment]
> What is not working exactly?

It just says "Coming Soon!". There is nothing one can do, except of setting it up.
