### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by nutpantz** [Husseinfo/interfast#4]
I'm not sure where you plan to go with this app.
Honestly the best app i have found is ifasting https://play.google.com/store/apps/details?id=com.ibuild.ifasting
Except it reports back to home a lot.
It has all the features i could ever want.
Weight tracking, water (which i don't use) and customize fasts (i do 96\1 fasts).
You should look at it for as a well designed app with great features. For inspiration.

I will be watching your app to see how it progresses, and will switch as soon as it's close to feature complete.

**Comment by Husseinfo** [comment]
Hello, thanks for sharing this!
I actually planned it to be as simple as possible in order to make it easy to getting started with intermittent fasting.
